import Navbar from "@/components/Navbar";
import "./globals.css";
import { Poppins } from "next/font/google";
import AuthProvider from "@/components/AuthProvider/AuthProvider";

const poppins = Poppins({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <Navbar />
          <div className="mt-16 container mx-auto text-gray-200 ">
            {children}
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
